# Rust formatting configuration

edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_block_trailing_comma = false
force_multiline_blocks = false
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true